name: cv_pro
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  pdf: ^3.10.8
  printing: ^5.12.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  isar_generator: ^3.1.0+1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
