name: cv_pro
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  pdf: ^3.10.8
  printing: ^5.12.0
  url_launcher: ^6.2.6
  flutter_image_compress: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  video_player_platform_interface: ^6.4.0


dev_dependencies:
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  image_cropper: ^9.1.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/
    - assets/images/background_fly.webp
    - assets/images/background_pattern.webp
    - assets/images/unknown_person.png
    - assets/fonts/MaterialIcons-Regular.ttf
    - assets/images/face_AI.webp
    - assets/fonts/Lato-Regular.ttf
    - assets/fonts/Lato-Bold.ttf
    - assets/video/animation_video.mp4