name: cv_pro
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# ===================================================================
# Dependencies: Packages your app needs to run.
# ===================================================================
dependencies:
  flutter:
    sdk: flutter

  # Icons that are commonly used.
  cupertino_icons: ^1.0.6

  # These were moved from dev_dependencies because the app needs them to run.
  flutter_riverpod: ^2.5.1
  pdf: ^3.10.8
  printing: ^5.12.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

# ===================================================================
# Dev Dependencies: Packages for development and testing ONLY.
# ===================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  # to encourage good coding practices.
  flutter_lints: ^3.0.0

# ===================================================================
# Flutter-specific configurations.
# ===================================================================
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # This section is VERY IMPORTANT for loading fonts into the PDF.
  assets:
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
